import java.awt.Font;
 import java.awt.*;

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:309855:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  start_pressed=true;
  button1.setVisible(false);
  textfield1.setVisible(false);
  name = textfield1.getText();
} //_CODE_:button1:309855:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:869927:
  println();
} //_CODE_:textfield1:869927:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 911, 255, 100, 60);
  button1.setText("START");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 881, 187, 150, 30, G4P.SCROLLBARS_NONE);
  textfield1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  textfield1.setOpaque(false);
  textfield1.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 30, 85, 1885, 43);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("My label");
  label1.setOpaque(false);
  label1.setVisible(false);
 label1.setFont(new Font("Monospaced", Font.PLAIN, 30));
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 
GLabel label1; 
public void showText(String text){
label1.setText(text);
label1.setVisible(true);


}
